import io
import datetime
import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.colors import HexColor
from reportlab.graphics import renderPDF
from svglib.svglib import svg2rlg

# Official RO Identity
RO_BLUE = HexColor('#21357F')
LOGO_PATH = r"C:\Users\63039\Videos\workstation\Workstation\doc.svg"

# Register Nirmala UI for Trilingual (Tamil/Hindi) support
# Nirmala.ttc is standard on Windows and supports all Indian languages
try:
    font_path = "C:/Windows/Fonts/Nirmala.ttc"
    # reportlab can sometimes handle .ttc collections directly
    pdfmetrics.registerFont(TTFont('Nirmala', font_path))
    UNICODE_FONT = 'Nirmala'
except Exception as e:
    print(f"Font Load Error: {e}")
    UNICODE_FONT = 'Helvetica' # Fallback to standard

def draw_ro_template(canvas, doc):
    """Draws the high-fidelity RO stationary header and footer on every page."""
    canvas.saveState()
    
    # 1. Logo at Top Left
    import os
    if os.path.exists(LOGO_PATH):
        try:
            drawing = svg2rlg(LOGO_PATH)
            # Scale logo (approx 0.5 inch height)
            factor = (0.55 * inch) / drawing.height
            drawing.width *= factor
            drawing.height *= factor
            drawing.scale(factor, factor)
            renderPDF.draw(drawing, canvas, 0.5 * inch, 10.3 * inch)
        except:
            pass

    # 2. Regional Office Title Bar (Blue Background)
    canvas.setFillColor(RO_BLUE)
    canvas.rect(0.5 * inch, 10.05 * inch, 7.5 * inch, 0.22 * inch, fill=1, stroke=0)
    
    canvas.setFillColor(colors.white)
    canvas.setFont(UNICODE_FONT, 9)
    # Centered trilingual designation
    ro_title = "Regional Office, Dindigul | மண்டல அலுவலகம், திண்டுக்கல் | क्षेत्रीय कार्यालय, दिण्डुक्कल"
    canvas.drawCentredString(4.25 * inch, 10.11 * inch, ro_title)
    
    # 3. Address & Communication (Compact, below the bar)
    canvas.setFillColor(colors.black)
    canvas.setFont(UNICODE_FONT, 8)
    address_line1 = "17-i, First Floor, Pensioner Street, Palani Road, Dindigul - 624001"
    comm_line = "Phone: 89259 53933 | Email: 3933ro@iob.bank.in"
    
    canvas.drawCentredString(4.25 * inch, 9.9 * inch, address_line1)
    canvas.drawCentredString(4.25 * inch, 9.78 * inch, comm_line)
    
    # 4. Secondary Divider Line
    canvas.setStrokeColor(RO_BLUE)
    canvas.setLineWidth(0.5)
    canvas.line(0.5 * inch, 9.7 * inch, 8.0 * inch, 9.7 * inch)
    
    # 5. Footer with Branding
    canvas.line(0.5 * inch, 0.75 * inch, 8.0 * inch, 0.75 * inch)
    canvas.setFont(UNICODE_FONT, 7)
    canvas.setFillColor(colors.grey)
    footer_text = "Generated by RO Workstation Control Center | Confidential | Page " + str(doc.page)
    canvas.drawCentredString(4.25 * inch, 0.5 * inch, footer_text)
    
    canvas.restoreState()

def generate_mis_report(df, date_str, sol="All Branches"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=1.2*inch, bottomMargin=1*inch)
    elements = []
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'ROTitle',
        parent=styles['Heading1'],
        textColor=RO_BLUE,
        fontName=UNICODE_FONT,
        alignment=1,
        spaceAfter=20
    )
    
    subtitle_style = ParagraphStyle(
        'ROSubtitle',
        parent=styles['Heading2'],
        textColor=RO_BLUE,
        fontName=UNICODE_FONT,
        spaceAfter=12
    )
    
    body_style = ParagraphStyle(
        'ROBody',
        parent=styles['Normal'],
        fontName=UNICODE_FONT,
        fontSize=10,
        leading=12
    )
    
    # Content
    elements.append(Paragraph("Performance MIS Report", title_style))
    elements.append(Paragraph(f"Date: {date_str} | Entity: {sol}", body_style))
    elements.append(Spacer(1, 0.25 * inch))
    
    if not df.empty:
        total_adv = df['Total Advances'].sum()
        total_dep = df['Total Deposits'].sum()
        cd_ratio = (total_adv / total_dep * 100) if total_dep > 0 else 0
        total_npa = df['NPA'].sum() if 'NPA' in df.columns else 0
        npa_pct = (total_npa / total_adv * 100) if total_adv > 0 else 0
        
        summary_data = [
            ["Metric", "Value"],
            ["Total Advances", f"{total_adv:,.2f}"],
            ["Total Deposits", f"{total_dep:,.2f}"],
            ["CD Ratio", f"{cd_ratio:,.2f}%"],
            ["Total NPA", f"{total_npa:,.2f}"],
            ["NPA %", f"{npa_pct:,.2f}%"]
        ]
        
        t = Table(summary_data, colWidths=[2.5 * inch, 1.5 * inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), RO_BLUE),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, -1), UNICODE_FONT),
            ('FONTSIZE', (0, 0), (-1, 0), 11),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
        ]))
        elements.append(Paragraph("Regional Overview", subtitle_style))
        elements.append(t)
        elements.append(Spacer(1, 0.5 * inch))
        
        # Branch Table
        if len(df) > 1:
            elements.append(Paragraph("Branch-wise Comparative", subtitle_style))
            top_branches = df.sort_values('Total Advances', ascending=False).head(20)
            branch_data = [["SOL", "Advances", "Deposits", "NPA %"]]
            for _, row in top_branches.iterrows():
                branch_data.append([
                    str(row['SOL']),
                    f"{row['Total Advances']:,.2f}",
                    f"{row['Total Deposits']:,.2f}",
                    f"{row['NPA %']:,.2f}%"
                ])
            
            bt = Table(branch_data, colWidths=[1 * inch, 1.5 * inch, 1.5 * inch, 1 * inch])
            bt.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, 0), RO_BLUE),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, -1), UNICODE_FONT),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTSIZE', (0, 0), (-1, -1), 9),
            ]))
            elements.append(bt)
    
    doc.build(elements, onFirstPage=draw_ro_template, onLaterPages=draw_ro_template)
    buffer.seek(0)
    return buffer.getvalue()

def generate_ro_anniversary_letter(anniversary):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=1.5*inch, bottomMargin=1*inch)
    elements = []
    
    styles = getSampleStyleSheet()
    body_style = ParagraphStyle(
        'LetterBody',
        parent=styles['Normal'],
        fontName=UNICODE_FONT,
        fontSize=11,
        leading=15,
        spaceAfter=15
    )
    
    sign_style = ParagraphStyle(
        'SignStyle',
        parent=styles['Normal'],
        fontName=UNICODE_FONT,
        alignment=2,
        spaceBefore=40
    )
    
    # Ref and Date
    elements.append(Paragraph(f"Ref: RO/DGL/PLNG/2026-27/{anniversary['code']}", body_style))
    elements.append(Paragraph(f"Date: {datetime.date.today().strftime('%d.%m.%Y')}", body_style))
    elements.append(Spacer(1, 0.25 * inch))
    
    # Recipient
    elements.append(Paragraph(f"To,<br/>The Branch Manager,<br/>{anniversary['name']} Branch ({anniversary['code']}).", body_style))
    elements.append(Spacer(1, 0.25 * inch))
    
    # Subject
    elements.append(Paragraph(f"<b>Subject: Observance of Special Business Fortnight - Foundation Day ({anniversary['years']} Years)</b>", body_style))
    elements.append(Spacer(1, 0.25 * inch))
    
    # Body (Trilingual spirit in text)
    text = (
        f"Heartiest congratulations to the team at <b>{anniversary['name']}</b> on the upcoming "
        f"<b>{anniversary['years']}th Foundation Day</b> to be celebrated on {anniversary['anniversary_date'].strftime('%d %B %Y')}."
        "<br/><br/>"
        "To commemorate this milestone, the Regional Office advises the branch to run a <b>Special Business Fortnight</b>. "
        "Focus should be on maximizing deposit mobilization and organizing local customer meets to strengthen our community presence."
        "<br/><br/>"
        "We wish you and your staff a highly successful campaign."
    )
    elements.append(Paragraph(text, body_style))
    
    # Closing signature block (Trilingual)
    elements.append(Paragraph("With best wishes / வாழ்த்துக்களுடன் / शुभकामनाओं के साथ,", sign_style))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph("<b>Regional Manager / மண்டல மேலாளர் / क्षेत्रीय प्रबंधक</b>", sign_style))
    
    doc.build(elements, onFirstPage=draw_ro_template, onLaterPages=draw_ro_template)
    buffer.seek(0)
    return buffer.getvalue()
