credentials:
  usernames:
    admin:
      email: admin@bank.local
      name: System Admin
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjEqG5Yn3u # hashed later in real app
      role: RO_Admin
      department: ALL
    rm:
      email: rm@bank.local
      name: Regional Manager
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjEqG5Yn3u
      role: RM
      department: ALL
    crmd_head:
      email: crmd_head@bank.local
      name: CRMD Head
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjEqG5Yn3u
      role: Dept_Head
      department: CRMD
    fi_head:
      email: fi_head@bank.local
      name: FI Head
      password: $2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjEqG5Yn3u
      role: Dept_Head
      department: FI
cookie:
  expiry_days: 30
  key: random_signature_key
  name: ro_workstation_cookie
pre-authorized:
  emails:
  - admin@bank.local
